helm

diff --git a/helm/templates/loadgenerator.yaml b/helm/templates/loadgenerator.yaml
--- a/helm/templates/loadgenerator.yaml
+++ b/helm/templates/loadgenerator.yaml
@@ -1,15 +1,71 @@
-apiVersion: networking.k8s.io/v1
-kind: Ingress
+---
+apiVersion: apps/v1
+kind: Deployment
 metadata:
-  name: {{ .Chart.Name }}
+  name: {{ .Values.loadGenerator.name }}
+  namespace: {{ .Release.Namespace }}
 spec:
-  rules:
-    - host: {{ pluck .Values.global.env .Values.host | first | default .Values.host._default }}
-      http:
-        paths:
-          - path: /
-            backend:
-              service:
-                name: {{ .Chart.Name }}
-                port:
-                  number: 8080
+  selector:
+    matchLabels:
+      app: {{ .Values.loadGenerator.name }}
+  replicas: 1
+  template:
+    metadata:
+      labels:
+        app: {{ .Values.loadGenerator.name }}
+    spec:
+      serviceAccountName: default
+      terminationGracePeriodSeconds: 5
+      restartPolicy: Always
+      securityContext:
+        fsGroup: 1000
+        runAsGroup: 1000
+        runAsNonRoot: true
+        runAsUser: 1000
+      {{- if .Values.loadGenerator.checkFrontendInitContainer }}
+      initContainers:
+      - command:
+        - /bin/sh
+        - -exc
+        - |
+          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+          if test $STATUSCODE -ne 200; then
+              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+              exit 1
+          fi
+        name: frontend-check
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - all
+          privileged: false
+          readOnlyRootFilesystem: true
+        image: busybox:latest
+        env:
+        - name: FRONTEND_ADDR
+          value: "{{ .Values.frontend.name }}:80"
+      {{- end }}
+      containers:
+      - name: main
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - all
+          privileged: false
+          readOnlyRootFilesystem: true
+        image: {{ .Values.images.repository }}/{{ .Values.loadGenerator.name }}:{{ .Values.images.tag | default .Chart.AppVersion }}
+        env:
+        - name: FRONTEND_ADDR
+          value: "{{ .Values.frontend.name }}:80"
+        - name: USERS
+          value: "10"
+        resources:
+          requests:
+            cpu: 300m
+            memory: 256Mi
+          limits:
+            cpu: 500m
+            memory: 512Mi
